[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel
build_src_filter = +<esp32_ddp_ws2812b.cpp>
upload_speed = 460800
